//
//  StoriesStabData.swift
//  TravelSchedule
//
//  Created by Demain Petropavlov on 25.04.2025.
//

import SwiftUI

@MainActor
final class StoriesStabData: ObservableObject {
    
    static let shared = StoriesStabData()
    
    @Published var stories: [Story] = [
        Story(small: .preview1,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big1,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big2,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview2,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big3,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big4,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview3,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big5,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big6,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview4,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big7,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big8,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview5,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big9,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big10,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview6,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big11,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big12,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview7,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big13,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big14,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview8,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big15,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big16,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)]),
        Story(small: .preview9,
              title: Constants.shortTextTitle,
              isViewed: false,
              story: [ContentStory(big: .big17,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription),
                      ContentStory(big: .big18,
                                   title: Constants.longTextTitle,
                                   description: Constants.longTextDescription)])
    ]
}
