//
//  StoriesStabData.swift
//  TravelSchedule
//
//  Created by Demain Petropavlov on 25.04.2025.
//

import SwiftUI

@MainActor
final class StoriesStabData: ObservableObject {
    
    static let shared = StoriesStabData()
    
    @Published var stories: [Story] = [
        Story(small: .preview1,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big1,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big2,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview2,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big3,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big4,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview3,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big5,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big6,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview4,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big7,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big8,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview5,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big9,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big10,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview6,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big11,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big12,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview7,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big13,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big14,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview8,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big15,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big16,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
        Story(small: .preview9,
              title: "Text Text Text...",
              isViewed: false,
              story: [ContentStory(big: .big17,
                                   title: "Text Text Text...",
                                   description: "Text Text Text..."),
                      ContentStory(big: .big18,
                                   title: "Text Text Text...",
                                   description: "Text Text Text...")]),
    ]
}
